/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LangSplatRouteImport } from "./routes/$lang/$";
import { Route as IndexRouteImport } from "./routes/index";

const IndexRoute = IndexRouteImport.update({
	getParentRoute: () => rootRouteImport,
	id: "/",
	path: "/",
} as any);
const LangSplatRoute = LangSplatRouteImport.update({
	getParentRoute: () => rootRouteImport,
	id: "/$lang/$",
	path: "/$lang/$",
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/$lang/$": typeof LangSplatRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/$lang/$": typeof LangSplatRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/$lang/$": typeof LangSplatRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/$lang/$";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/$lang/$";
	id: "__root__" | "/" | "/$lang/$";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	LangSplatRoute: typeof LangSplatRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/$lang/$": {
			id: "/$lang/$";
			path: "/$lang/$";
			fullPath: "/$lang/$";
			preLoaderRoute: typeof LangSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	LangSplatRoute: LangSplatRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
